"""Make password_hash nullable for guest users

Revision ID: 315d89ec3e2d
Revises: 6bfbdba56ffb
Create Date: 2025-10-24 16:27:04.661400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '315d89ec3e2d'
down_revision = '6bfbdba56ffb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)

    # ### end Alembic commands ###
